import type { Metadata } from 'next';
import './globals.css';
import SignIn from '@/components/signin/Signin';
import localFont from 'next/font/local';
import MapsProvider from '@/provider/MapsProvider';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const clientId = process.env.NAVER_MAPS_CLIENT_ID!;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MapsProvider clientId={clientId}>
        <body className={pretendard.className}>
          <header className="w-full h-[130px] bg-gray-100">헤더</header>
          <main>{children}</main>
          <SignIn />
        </body>
      </MapsProvider>
    </html>
  );
}
