import type { Metadata } from 'next';
import './globals.css';
import SignIn from '@/components/signin/Signin';
import Header from '@/components/Header';
import SideNav from '@/components/SideNav';

import localFont from 'next/font/local';
import MapsProvider from '@/provider/MapsProvider';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const clientId = process.env.NAVER_MAPS_CLIENT_ID!;

const getRnewalToken = async () => {
  try {
    const response = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/v1/reissue`, {
      method: 'POST',
      credentials: 'include',
    });
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.error(error);
  }
};

getRnewalToken();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MapsProvider clientId={clientId}>
        <body className={pretendard.className}>
          <SignIn />
          <Header />
          <main className="">{children}</main>
          <SideNav />
        </body>
      </MapsProvider>
    </html>
  );
}
