import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SignIn from '@/components/signin/Signin';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>
        {children}
        <SignIn />
      </body>
    </html>
  );
}
