const timeList = [
  "5:00",
  "6:00",
  "7:00",
  "8:00",
  "9:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
];

const daysList = [
  {
    code: "8",
    codeKorName: "주중",
    codeEngName: "WEEKDAY",
    mngItem1: "월,화,수,목,금요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 10,
  },
  {
    code: "9",
    codeKorName: "주말",
    codeEngName: "WEEKEND",
    mngItem1: "토,일요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 11,
  },
  {
    code: "1",
    codeKorName: "월",
    codeEngName: "MONDAY",
    mngItem1: "월요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 3,
  },
  {
    code: "2",
    codeKorName: "화",
    codeEngName: "TUESDAY",
    mngItem1: "화요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 4,
  },
  {
    code: "3",
    codeKorName: "수",
    codeEngName: "WEDNESDAY",
    mngItem1: "수요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 5,
  },
  {
    code: "4",
    codeKorName: "목",
    codeEngName: "THURSDAY",
    mngItem1: "목요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 6,
  },
  {
    code: "5",
    codeKorName: "금",
    codeEngName: "FRIDAY",
    mngItem1: "금요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 7,
  },
  {
    code: "6",
    codeKorName: "토",
    codeEngName: "SATURDAY",
    mngItem1: "토요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 8,
  },
  {
    code: "7",
    codeKorName: "일",
    codeEngName: "SUNDAY",
    mngItem1: "일요일",
    mngItem2: "",
    mngItem3: "",
    mngItem4: "",
    description: "",
    useYn: "Y",
    codeSeq: 9,
  },
];

export { timeList, daysList };
